<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style type="text/css">
.color-change-2x {
	animation: color-change-2x 2s linear infinite alternate both;
}
div{
	width:500px;
	height:500px;

}

/* ----------------------------------------------
 * Generated by Animista on 2022-8-23 12:54:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation color-change-2x
 * ----------------------------------------
 */
@keyframes color-change-2x {
  0% {
    background: #19dcea;
  }
  100% {
    background: #b22cff;
  }
}


</style>
<title>Insert title here</title>
</head>
<body class="color-change-2x">
<div class="color-change-2x">
배경test
</div>
</body>
</html>